# Generated by Django 5.2.17 on 2026-10-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_mentoring_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AlterModelOptions(
            name='competencia',
            options={'verbose_name': 'competência', 'verbose_name_plural': 'competências'},
        ),
        migrations.AlterModelOptions(
            name='mestre',
            options={'verbose_name': 'mestre', 'verbose_name_plural': 'mestres'},
        ),
        migrations.AlterModelOptions(
            name='mestrealuno',
            options={'verbose_name': 'vínculo de mentoria', 'verbose_name_plural': 'vínculos de mentoria'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name': 'reunião', 'verbose_name_plural': 'reuniões'},
        ),
        migrations.AlterModelOptions(
            name='reuniaotarefa',
            options={'verbose_name': 'tarefa de reunião', 'verbose_name_plural': 'tarefas de reunião'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='bl_usuario_ativo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Usuário ativo?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='txt_area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='txt_categoria_cargo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoria do cargo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='txt_linha_servico',
            field=models.CharField(blank=True, max_length=50, verbose_name='Linha de serviço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='txt_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='txt_nivel_ingles',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nível de inglês'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='dt_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='dt_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='txt_competencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Competência'),
        ),
        migrations.AlterField(
            model_name='mestre',
            name='bl_usuario_ativo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Usuário ativo?'),
        ),
        migrations.AlterField(
            model_name='mestre',
            name='dt_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='mestre',
            name='dt_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='mestrealuno',
            name='dt_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='mestrealuno',
            name='txt_ano_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ano fiscal'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='dt_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='dt_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='txt_comentario',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='reuniaotarefa',
            name='dt_atualizacao',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='reuniaotarefa',
            name='dt_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='reuniaotarefa',
            name='dt_criacao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='reuniaotarefa',
            name='nr_prazo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo (dias)'),
        ),
        migrations.AlterField(
            model_name='reuniaotarefa',
            name='txt_observacao',
            field=models.TextField(blank=True, max_length=200, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='reuniaotarefa',
            name='txt_status',
            field=models.CharField(choices=[('0', 'Pendente'), ('1', 'Em andamento'), ('2', 'Concluído')], default='0', max_length=1),
        ),
    ]
